/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;


import Persistencia.ArchivoCita;
import Persistencia.ArchivoMedico;
import Persistencia.ArchivoPaciente;

/**
 *
 * @author GERALDIN
 */
public class Menu extends javax.swing.JFrame {

    public static ArchivoPaciente arP = new ArchivoPaciente();
    public static ArchivoMedico arM = new ArchivoMedico();
    public static ArchivoCita arC = new ArchivoCita();

    /**
     * Creates new form Menu
     */
    public Menu() {
        setLocationRelativeTo(null);
        initComponents();
        arM.LeerMedico();
        arP.LeerPaciente();
        arC.LeerCita();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        medico = new javax.swing.JMenuItem();
        paciente = new javax.swing.JMenuItem();
        cita = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/images.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 210));

        jMenu3.setText("AGREGAR");

        medico.setText("MEDICO");
        medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoActionPerformed(evt);
            }
        });
        jMenu3.add(medico);

        paciente.setText("PACIENTE");
        paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteActionPerformed(evt);
            }
        });
        jMenu3.add(paciente);

        cita.setText("CITA");
        cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citaActionPerformed(evt);
            }
        });
        jMenu3.add(cita);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        setBounds(0, 0, 258, 270);
    }// </editor-fold>//GEN-END:initComponents

    private void pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteActionPerformed
        new AgregarPaciente().setVisible(true);
    }//GEN-LAST:event_pacienteActionPerformed

    private void medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoActionPerformed
        new AgregarMedico().setVisible(true);
    }//GEN-LAST:event_medicoActionPerformed

    private void citaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citaActionPerformed
        new AgregarCita().setVisible(true);
    }//GEN-LAST:event_citaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem medico;
    private javax.swing.JMenuItem paciente;
    // End of variables declaration//GEN-END:variables
}
